### ISSUE TITLE
Update example options in readme

### ISSUE THREAD

**Issue by realyukii** [itzngga/Roxy#26]
for postgresql, i use this way:
```
PostgresDsn: &options.PostgresDSN{
	Username: os.Getenv("PG_USERNAME"),
	Password: os.Getenv("PG_PASSWORD"),
	Database: os.Getenv("PG_DB_NAME"),
	Port: os.Getenv("PG_PORT"),
	SslMode: "disable",
	TimeZone: "Asia/Jakarta",
},
```

because current example throw an error: `multiple-value options.NewPostgresDSN("username", "password", "dbname", "port", "disable", "Asia/Jakarta") (value of type (*"github.com/itzngga/Roxy/options".PostgresDSN, error)) in single-value contextcompiler[TooManyValues](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#TooManyValues)`

**Comment by itzngga** [comment]
fixed on [777cb78](https://github.com/itzngga/Roxy/commit/777cb78e263d10610cf5a46c2aad5e3b350b085a)
